// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDya5cz4SAx_1HepY-6Jei85hnmAe40o',
    appId: '1:889655193973:web:b4f1668622f922e968233c',
    messagingSenderId: '889655193973',
    projectId: 'messenger-53de0',
    authDomain: 'messenger-53de0.firebaseapp.com',
    storageBucket: 'messenger-53de0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBuBjUuU2IX3aLFI0F4u-w3N3U5cvW2A',
    appId: '1:889655193973:android:dcfafc71b3ad7c1d68233c',
    messagingSenderId: '889655193973',
    projectId: 'messenger-53de0',
    storageBucket: 'messenger-53de0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxoziUp0uUWlgZvYcrxWKbg_tuVa92uA4',
    appId: '1:889655193973:ios:7ca5dfdd4af9cc2968233c',
    messagingSenderId: '889655193973',
    projectId: 'messenger-53de0',
    storageBucket: 'messenger-53de0.firebasestorage.app',
    iosClientId: '889655193973-v81a9qsvs1biqgs5pq38qun80tlc916n.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger',
  );
}
